name: Bad Dog
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56229
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#293935'
    - '#9b3334'
    - '#765751'
    - '#c9b78f'
    - '#a99d7d'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
